Refactor: Relocate function

diff --git a/bin/git-bump-version-tag b/bin/git-bump-version-tag
--- a/bin/git-bump-version-tag
+++ b/bin/git-bump-version-tag
@@ -210,39 +210,6 @@ insist_cmd () {
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
-insist_tag_commit_unversioned_or_same_version () {
-  local version_tag="$1"
-  local tag_commit="$2"
-
-  local existing_tags
-  existing_tags="$(git_versions_tagged_for_commit_object "${tag_commit}")"
-
-  if [ -n "${existing_tags}" ]; then
-    local num_versions="$(echo "${existing_tags}" | wc -l)"
-
-    if [ ${num_versions} -gt 1 ]; then
-      >&2 echo "ERROR: The target commit has more than one version tag:"
-      >&2 echo "${existing_tags}"
-
-      exit_1
-    fi
-
-    local commit_version="${existing_tags}"
-
-    if [ "${commit_version}" != "${version_tag}" ]; then
-      # We could allow this, but seems like an unlikely use case,
-      # or rather, I can't think of a valid end user use case for
-      # tagging the same commit with more than one version, so
-      # block it.
-      >&2 echo "ERROR: The target commit is already version-tagged: ${commit_version}"
-
-      exit_1
-    fi
-  fi
-}
-
-# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
-
 print_git_remote_default_branch_name () {
   local remote_name="$1"
 
@@ -1387,6 +1354,39 @@ print_smaller_vers_for_same_patch () {
     | command sort -k1,1r -k2,2n \
     | command head -n1 \
     | command sed -E "s/^[^,]*, [^,]*, //"
+}
+
+# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
+
+insist_tag_commit_unversioned_or_same_version () {
+  local version_tag="$1"
+  local tag_commit="$2"
+
+  local existing_tags
+  existing_tags="$(git_versions_tagged_for_commit_object "${tag_commit}")"
+
+  if [ -n "${existing_tags}" ]; then
+    local num_versions="$(echo "${existing_tags}" | wc -l)"
+
+    if [ ${num_versions} -gt 1 ]; then
+      >&2 echo "ERROR: The target commit has more than one version tag:"
+      >&2 echo "${existing_tags}"
+
+      exit_1
+    fi
+
+    local commit_version="${existing_tags}"
+
+    if [ "${commit_version}" != "${version_tag}" ]; then
+      # We could allow this, but seems like an unlikely use case,
+      # or rather, I can't think of a valid end user use case for
+      # tagging the same commit with more than one version, so
+      # block it.
+      >&2 echo "ERROR: The target commit is already version-tagged: ${commit_version}"
+
+      exit_1
+    fi
+  fi
 }
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
