Feature: Allow double-versioning same commit if dropping pre-release

diff --git a/bin/git-bump-version-tag b/bin/git-bump-version-tag
--- a/bin/git-bump-version-tag
+++ b/bin/git-bump-version-tag
@@ -1140,11 +1140,13 @@ git_tag_remote_push () {
 #
 #   - Now the remote has two version tags on the same commit.
 #
-# - This app already prevents double-versioning locally. It'll
-#   refuse to run if ${tag_commit} already has a version different
-#   than ${version_tag}. See:
+# - This app prevents double-versioning locally in most cases.
+#   It'll refuse to run if ${tag_commit} already has a version
+#   different than ${version_tag}, except if that ${tag_commit}
+#   has a prerelease version, and ${version_tag} is a release.
+#   See:
 #
-#     insist_tag_commit_unversioned_or_same_version
+#     insist_tag_commit_unversioned_or_same_version_or_dropping_prerelease
 #
 #   - So the scenario described only happens if the user
 #     fails to delete remote tags after deleting locally.
@@ -1391,9 +1393,16 @@ print_smaller_vers_for_same_patch () {
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
-insist_tag_commit_unversioned_or_same_version () {
+insist_tag_commit_unversioned_or_same_version_or_dropping_prerelease () {
   local version_tag="$1"
   local tag_commit="$2"
+  local remote_name="$3"
+  local remote_branch="$4"
+
+  local refname="$(git_sha_shorten "${tag_commit}")"
+  if [ "${remote_name}" != "${BUMP_SKIP_REMOTE}" ]; then
+    refname="${remote_name}/${remote_branch}"
+  fi
 
   local existing_tags
   existing_tags="$(git_versions_tagged_for_commit_object "${tag_commit}")"
@@ -1402,7 +1411,7 @@ insist_tag_commit_unversioned_or_same_version () {
     local num_versions="$(echo "${existing_tags}" | wc -l)"
 
     if [ ${num_versions} -gt 1 ]; then
-      >&2 echo "ERROR: The target commit has more than one version tag:"
+      >&2 echo "ERROR: The target commit “${refname}” already has more than one version tag:"
       >&2 echo "${existing_tags}"
 
       exit_1
@@ -1410,16 +1419,44 @@ insist_tag_commit_unversioned_or_same_version () {
 
     local commit_version="${existing_tags}"
 
+    # There's one Use Case for allowing two versions on the same commit:
+    # - One prerelease, One release.
+    # If you have another Use Case, plumb it and PR it, or open an Issue.
+    # - Because I'd love to learn of other use cases for multi-versioning.
     if [ "${commit_version}" != "${version_tag}" ]; then
-      # We could allow this, but seems like an unlikely use case,
-      # or rather, I can't think of a valid end user use case for
-      # tagging the same commit with more than one version, so
-      # block it.
-      >&2 echo "ERROR: The target commit is already version-tagged: ${commit_version}"
+      if is_version_pre_release "${commit_version}" \
+        && is_version_normal "${version_tag}" \
+        && is_version_gt_version "${version_tag}" "${commit_version}" \
+      ; then
+        >&2 echo "BWARE: Double-tagging commit: Adding Normal version atop Pre-release"
+      else
+        >&2 echo "ERROR: The target commit “${refname}” is already version-tagged: ${commit_version}"
+        >&2 echo "- Hint: You can use a Normal version atop a Pre-release, but that's it."
 
-      exit_1
+        exit_1
+      fi
     fi
   fi
+}
+
+# ***
+
+is_version_pre_release () {
+  local version_full="$1"
+
+  local version_normal
+  version_normal="$(strip_prerelease "${version_full}")"
+
+  [ "${version_full}" != "${version_normal}" ]
+}
+
+is_version_normal () {
+  local version_full="$1"
+
+  local version_normal
+  version_normal="$(strip_prerelease "${version_full}")"
+
+  [ "${version_full}" = "${version_normal}" ]
 }
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
@@ -1674,16 +1711,9 @@ prepare_push () {
   local commit_version
   commit_version="$(git_largest_version_tag --points-at ${tag_commit})"
   if [ -n "${commit_version}" ]; then
-    if [ "${commit_version}" != "${VERSION_TAG}" ]; then
-      local refname="${tag_commit}"
-      [ "${remote_name}" = "${BUMP_SKIP_REMOTE}" ] \
-        || refname="${remote_name}/${remote_branch}"
-
-      >&2 echo "ERROR: Commit “${refname}” is already versioned (${commit_version})," \
-        "and different than new version (${VERSION_TAG})"
-
-      exit_1
-    fi
+    # We'll compare ${commit_version} and ${VERSION_TAG} after the if-else.
+    # - See below:
+    #   insist_tag_commit_unversioned_or_same_version_or_dropping_prerelease
 
     # So that git_tag_local_add doesn't add same tag again.
     curr_version="${commit_version}"
@@ -1717,7 +1747,12 @@ prepare_push () {
     fi
   fi
 
-  insist_tag_commit_unversioned_or_same_version "${VERSION_TAG}" "${tag_commit}"
+  # This is similar to the [ "${commit_version}" != "${VERSION_TAG}" ] check
+  # above, but more robust. It checks no more than one tag already applied,
+  # and there is a pre-existing tag, verifies new tag > old tag, and that
+  # the new tag is normaling a pre-release version.
+  insist_tag_commit_unversioned_or_same_version_or_dropping_prerelease \
+    "${VERSION_TAG}" "${tag_commit}" "${remote_name}" "${remote_branch}"
 
   # *** Verify version order integrity between local and remote repos
 
