Improve: Use <UPSTREAM> arg to use git-bump to make inaugural push

diff --git a/bin/git-bump-version-tag b/bin/git-bump-version-tag
--- a/bin/git-bump-version-tag
+++ b/bin/git-bump-version-tag
@@ -394,8 +394,8 @@ print_git_remote_default_branch_name () {
   # because wc -l counts empty line.
   if [ -z "${branch_names}" ] || [ ${num_branches} -eq 0 ]; then
     if ! ${ACTION_DELETE}; then
-      >&2 echo "ERROR: No local branches found for remote “${remote_name}”" \
-        "Perhaps you need to fetch?"
+      >&2 echo "ERROR: No branches found for remote “${remote_name}”"
+      >&2 echo "- Use the <UPSTREAM> arg. if this is your first push"
 
       return 1
     fi
@@ -1619,7 +1619,11 @@ git_tag_remote_push () {
     fi
   else
     # Assume everything must be pushed.
-    upstream_ref="$(git_first_commit_sha)"
+    # - Use case: Fresh remote, hasn't been pushed yet,
+    #   and user specified <UPSTREAM> arg.
+    # This var. merely used for git_distance_between_commits,
+    # so leave blank to `git rev-list --count HEAD` count all.
+    upstream_ref=""
   fi
 
   local use_put_wise=false
@@ -2387,7 +2391,7 @@ git_bump_tag_vers_push () {
   remote_head_sha="$(resolve_remote_head_sha "${remote_name}" "${remote_branch}")" \
     || exit_1
 
-  insist_remote_head_is_ancestor_if_set "${remote_name}" "${remote_branch}" \
+  insist_remote_head_is_ancestor_if_set "${remote_name}" "${remote_branch}" "${remote_head_sha}" \
     || exit_1
 
   # Target commit, set to CLI arg if set, else remote/branch, or (scoped) HEAD.
@@ -2475,6 +2479,14 @@ resolve_remote_name () {
     if [ -z "${remote_name}" ]; then
       remote_name="$(resolve_remote_name_from_remotes "${version_tag}")" \
         || return 1
+    fi
+
+    if [ "${remote_name}" != "${BUMP_SKIP_REMOTE}" ]; then
+      must_remote_exists "${remote_name}" \
+        || return 1
+
+      # Fetch remote at least every hour (network call).
+      periodically_fetch "${remote_name}"
     fi
   fi
 
@@ -2571,8 +2583,9 @@ resolve_remote_branch () {
 insist_remote_head_is_ancestor_if_set () {
   local remote_name="$1"
   local remote_branch="$2"
+  local remote_head_sha="$3"
 
-  if [ -z "${remote_name}" ] || [ -z "${remote_branch}" ]; then
+  if [ -z "${remote_head_sha}" ]; then
 
     return 0
   fi
@@ -2597,19 +2610,13 @@ resolve_remote_head_sha () {
   # Unless there are no remotes, user must use "-" to skip this
   # remote check.
   if [ "${remote_name}" != "${BUMP_SKIP_REMOTE}" ]; then
-    must_remote_exists "${remote_name}" \
-      || return 1
-
-    # Fetch remote at least every hour (network call).
-    periodically_fetch "${remote_name}"
-
     if ! remote_head_sha="$(
       git_remote_branch_object_name "${remote_name}" "${remote_branch}"
     )"; then
-      >&2 echo "ERROR: Specified remote/branch not a recognized object:" \
+      >&2 echo "Specified remote branch does not exist:" \
         "“${remote_name}/${remote_branch}”"
 
-      return 1
+      return 0
     fi
   fi
 
