Improve: Allow greater alpha applied to normal-versioned commit
- Users could previously apply a normal version tag to the
  same commit as a pre-release version, if the normal tag
  was greater.

  - Use case: Some workflows (like EAPP) support auto-releasing
    from version tags, and this approach lets you apply an alpha
    tag, test it, and then apply a normal tag to make the normal
    release, without needing to introduce any new commits.

- This new behavior also lets user apply an alpha version tag
  greater than the existing normal tag.

  - Use case: Some workflows (like EAPP) send normal releases
    to a different index than alpha releases (e.g., to normal
    PyPI vs. test.PyPI), and they run automatically based on
    on the version tag.

    As such, so that inter-org dependencies always use the
    latest package versions, when publishing an alpha build
    to the test index, all inter-org dependencies, regardless
    of whether they were just released normal or not, need to
    deploy their latest code to the test index.

    - So now, in either case, whether a commit is tagged with
      a pre-release version first, and then a greater normal
      version later; or, if a commit is tagged with a normal
      version first, and then a greater pre-release version
      later; we want to ensure that CI workflows that send
      normal releases and pre-releases to different indices
      will work properly.

diff --git a/bin/git-bump-version-tag b/bin/git-bump-version-tag
--- a/bin/git-bump-version-tag
+++ b/bin/git-bump-version-tag
@@ -1569,14 +1569,41 @@ insist_tag_commit_unversioned_or_same_version_or_dropping_prerelease () {
     # If you have another Use Case, plumb it and PR it, or open an Issue.
     # - Because I'd love to learn of other use cases for multi-versioning.
     if [ "${commit_version}" != "${version_tag}" ]; then
-      if is_version_pre_release "${commit_version}" \
-        && is_version_normal "${version_tag}" \
-        && is_version_gt_version "${version_tag}" "${commit_version}" \
-      ; then
-        >&2 echo "BWARE: Double-tagging commit: Adding Normal version atop Pre-release"
+      local invalid_version=false
+      local error_hint=""
+
+      if is_version_gt_version "${version_tag}" "${commit_version}"; then
+        # Newer tag greater than existing tag.
+        if is_version_pre_release "${commit_version}" \
+          && is_version_normal "${version_tag}" \
+        ; then
+          >&2 echo "BWARE: Double-tagging commit: Adding Normal version to Pre-release"
+        elif is_version_pre_release "${version_tag}" \
+          && is_version_normal "${commit_version}" \
+        ; then
+          >&2 echo "BWARE: Double-tagging commit: Adding Pre-release version to Normal"
+        else
+          # Both versions are normal or both are pre-release.
+          invalid_version=true
+
+          error_hint="- Hint: You can mix a normal version and a pre-release version, but that's it."
+        fi
       else
+        # Newer tag less than existing tag.
+        invalid_version=true
+
+        version_type=""
+        if is_version_pre_release "${commit_version}"; then
+          version_type="normal"
+        else
+          version_type="pre-release"
+        fi
+        error_hint="- Hint: You could apply a ${version_type} version greater than ${commit_version}"
+      fi
+
+      if ${invalid_version}; then
         >&2 echo "ERROR: The target commit “${refname}” is already version-tagged: ${commit_version}"
-        >&2 echo "- Hint: You can use a Normal version atop a Pre-release, but that's it."
+        >&2 echo "${error_hint}"
 
         exit_1
       fi
