Feature: Sort & sign commits before bumping, à la git-put-wise

diff --git a/bin/git-bump-version-tag b/bin/git-bump-version-tag
--- a/bin/git-bump-version-tag
+++ b/bin/git-bump-version-tag
@@ -303,13 +303,21 @@ source_deps () {
 
   # Optional: git-put-wise, for 'identify_scope_ends_at'.
   # CXREF: https://github.com/DepoXy/git-put-wise#🥨
+  # - For color support:
+  #   ~/.kit/git/git-put-wise/deps/sh-logger/bin/logger.sh
+  # - For SCOPING_PREFIX, PRIVATE_PREFIX, etc.:
   #   ~/.kit/git/git-put-wise/lib/common_put_wise.sh
-  #   ~/.kit/git/git-put-wise/lib/dep_apply_confirm_patch_base.sh
+  # - For identify_scope_ends_at:
+  #   ~/.kit/git/git-put-wise/lib/dep_scoped_commits.sh
+  # - For put_wise_identify_rebase_boundary_and_remotes:
+  #   ~/.kit/git/git-put-wise/lib/dep_rebase_boundary.sh
   # SAVVY: common_put_wise.sh requires Bash (it uses `< <()`).
   if command -v git-put-wise > /dev/null; then
     local put_wise_bin="$(dirname -- "$(realpath -- "$(command -v git-put-wise)")")"
+    . "${put_wise_bin}/../deps/sh-logger/bin/logger.sh"
     . "${put_wise_bin}/../lib/common_put_wise.sh"
-    . "${put_wise_bin}/../lib/dep_apply_confirm_patch_base.sh"
+    . "${put_wise_bin}/../lib/dep_scoped_commits.sh"
+    . "${put_wise_bin}/../lib/dep_rebase_boundary.sh"
   fi
 }
 
@@ -1545,9 +1553,8 @@ git_tag_remote_push () {
   #   require user to push branch themselves before bumping).
   #   - Note that we previously bailed if ${remote_branch} is
   #     not the same as the local branch.
-  if ! "${skip_push_branch}"; then
-    echo_or_eval git push "\"${remote_name}\" \
-      \"${tag_commit}:refs/heads/${remote_branch}\""
+  if ! ${skip_push_branch}; then
+    git_branch_remote_push "${tag_commit}" "${remote_name}" "${remote_branch}"
 
     echo "✓ Pushed remote branch"
   fi
@@ -1574,6 +1581,27 @@ git_tag_remote_push () {
   echo_or_eval "git push \"${remote_name}\" \"refs/tags/${version_tag}\""
 
   echo "✓ Pushed remote tag"
+}
+
+# ***
+
+git_branch_remote_push () {
+  local tag_commit="$1"
+  local remote_name="$2"
+  local remote_branch="$3"
+
+  local use_put_wise=false
+
+  if is_put_wise_push_remote_same "${remote_name}" "${remote_branch}"; then
+    use_put_wise=true
+  fi
+
+  if ${use_put_wise}; then
+    git put-wise push
+  else
+    echo_or_eval git push "\"${remote_name}\" \
+      \"${tag_commit}:refs/heads/${remote_branch}\""
+  fi
 }
 
 # ***
@@ -2284,6 +2312,12 @@ git_bump_tag_vers_push () {
     "${remote_head_sha}" "${UPSTREAM_ARG}" \
     || exit_1
 
+  local PW_PUSH_REMOTE_RELEASE=""
+  sort_and_sign_and_re_resolve_tag_commit \
+    "${remote_name}" "${remote_branch}" \
+    "${remote_head_sha}" \
+    || exit_1
+
   # Now that the correct version is identified, replay the bump commands.
   # - If this feels wonky — that we called this function and parsed user
   #   args already — it is. It's an artifact of how the code evolved. But
@@ -2865,7 +2899,252 @@ push_or_delete () {
   fi
 }
 
+# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
+
+# USAGE: Opt-out git-put-wise using PUT_WISE_SKIP_REBASE=true
+# (or don't install git-put-wise).
+
+is_git_put_wise_sort_and_sign_enabled () {
+  command -v git-put-wise > /dev/null \
+    && ! ${PUT_WISE_SKIP_REBASE:-false}
+}
+
+# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
+
+sort_and_sign_and_re_resolve_tag_commit () {
+  local remote_name="$1"
+  local remote_branch="$2"
+  local remote_head_sha="$3"
+
+  if ! is_git_put_wise_sort_and_sign_enabled; then
+    # Means PUT_WISE_SKIP_REBASE=true, or git-put-wise not found.
+
+    return 0
+  fi
+
+  local REBASE_BOUNDARY=""
+  PW_PUSH_REMOTE_RELEASE=""
+  local already_sorted=false
+  resolve_rebase_boundary
+
+  if ${ACTION_CHECK} || ${ACTION_CURRENT} || ${ACTION_DELETE}; then
+
+    return 0
+  fi
+
+  local prev_head_sha
+  prev_head_sha="$(git_HEAD_commit_sha)"
+
+  sort_and_sign_commits_with_prompt_maybe "${REBASE_BOUNDARY}" "${already_sorted}"
+
+  local curr_head_sha
+  curr_head_sha="$(git_HEAD_commit_sha)"
+
+  if [ "${curr_head_sha}" != "${prev_head_sha}" ]; then
+    must_resolve_tag_commit_and_curr_version \
+      "${TAG_COMMIT_ARG}" "${VERSION_ARG}" \
+      "${remote_name}" "${remote_branch}" \
+      "${remote_head_sha}" "${UPSTREAM_ARG}" \
+      || exit_1
+  fi
+}
+
 # ***
+
+sort_and_sign_commits_with_prompt_maybe () {
+  local rebase_boundary="$1"
+  local already_sorted="$2"
+
+  if [ -z "${rebase_boundary}" ]; then
+    # Already sorted and signed.
+
+    return 0
+  fi
+
+  if git_is_same_commit "${rebase_boundary}" "HEAD"; then
+
+    return 0
+  fi
+
+  if is_sorted_and_signed_or_gpw_disabled "${rebase_boundary}"; then
+
+    return 0
+  fi
+
+  if prompt_user_to_sort_and_sign_commits "${rebase_boundary}" "${already_sorted}"; then
+    # Exits 0 or 11 if rebase_boundary is HEAD (nothing to resort/sign).
+    # - Run in subshell so this command doesn't exit.
+    # CXREF: ~/.kit/git/git-put-wise/lib/common_put_wise.sh
+    ( resort_and_sign_commits_before_push "${rebase_boundary}" \
+        ${_enable_gpg_sign:-true}
+    ) || exit_1
+  fi
+}
+
+# ***
+
+is_sorted_and_signed_or_gpw_disabled () {
+  local rebase_boundary="$1"
+
+  if ! is_git_put_wise_sort_and_sign_enabled; then
+    # Means PUT_WISE_SKIP_REBASE=true, or git-put-wise not found.
+
+    return 0
+  fi
+
+  if [ -z "${rebase_boundary}" ]; then
+    # put_wise_identify_rebase_boundary_and_remotes set rebase_boundary to
+    # empty string if rebase boundary could not be identified but all
+    # commits are sorted & signed. Or if PUT_WISE_SKIP_REBASE=true.
+
+    return 0
+  fi
+
+  if [ "${rebase_boundary}" = "${PUT_WISE_REBASE_ALL_COMMITS:-ROOT}" ]; then
+    # If put_wise_identify_rebase_boundary_and_remotes fails,
+    # resolve_rebase_boundary uses the magic "ROOT" gitref to
+    # indicate that user may want to sort & sign all commits.
+
+    return 1
+  fi
+
+  # ***
+
+  local enable_gpg_sign=true
+
+  # CXREF: ~/.kit/git/git-put-wise/lib/common_put_wise.sh
+  local gpg_sign
+  if ! gpg_sign="$( \
+    insist_print_gpg_sign_arg ${enable_gpg_sign} ${_insist_signing_key:-false}
+  )"; then
+    >&2 echo "GAFFE: Unreachable path [is_sorted_and_signed_or_gpw_disabled]"
+
+    return 1
+  fi
+
+  if [ -z "${gpg_sign}" ]; then
+    enable_gpg_sign=false
+  fi
+
+  # ***
+
+  # Sets already_sorted=true and returns 1 if sorted but not signed;
+  # Or sets already_sorted=false and returns 1 if not sorted; or
+  # returns 0 if sorted, and signed if requested.
+  # - Also prints "✓ Verified ..." message, if either or both verified.
+  # CXREF: ~/.kit/git/git-put-wise/lib/common_put_wise.sh
+  already_sorted=false
+  if is_already_sorted_and_signed "${rebase_boundary}" "${enable_gpg_sign}" \
+  ; then
+
+    return 0
+  fi
+
+  return 1
+}
+
+# ***
+
+prompt_user_to_sort_and_sign_commits () {
+  local rebase_boundary="$1"
+  local already_sorted="$2"
+
+  local nor_sorted=""
+  local sort_and=""
+  if ! ${already_sorted}; then
+    nor_sorted=" nor sorted"
+    sort_and="sort & "
+  fi
+
+  echo "You have not signed${nor_sorted} commits"
+
+  local rev_list_commits
+  rev_list_commits=$(print_git_rev_list_commits "${rebase_boundary}")
+
+  local n_commits
+  n_commits="$(git rev-list --count ${rev_list_commits})"
+
+  local n_commits_inflector=""
+  [ ${n_commits} -eq 1 ] || n_commits_inflector="s"
+
+  local commit_cnt="${n_commits} commit${n_commits_inflector}"
+
+  if [ "${rebase_boundary}" != "${PUT_WISE_REBASE_ALL_COMMITS:-ROOT}" ]; then
+    echo "- We suggest rebasing since this commit: ${rebase_boundary} (${commit_cnt})"
+  else
+    echo "- We suggest rebasing *everything* (${commit_cnt}) because no rebase boundary identified"
+  fi
+
+  # echo "- Those with “${SCOPING_PREFIX}” and “${PRIVATE_PREFIX}” commit messages"
+  # E.g., "Would you like to sign commits now?", and
+  #   "Would you like to sort & sign commits now?"
+  local msg="Would you like to ${sort_and}sign commits now"
+
+  local THE_CHOICE
+  ask_yesnoskip_maybe "${msg}" "Y"
+
+  [ $? -ne 0 ] && exit_1 || true
+
+  [ "${THE_CHOICE}" != "y" ] && return 1 || return 0
+}
+
+# ***
+
+resolve_rebase_boundary () {
+  # Use put-wise-push to determine rebase boundary.
+  # - This fails if version tag found after rebase boundary,
+  #   unless PW_OPTION_ORPHAN_TAGS=true.
+
+  # These vars are set by the next fcn. (aka local abuse):
+  local branch_name=""
+  local local_release=""
+  local remote_release=""
+  local remote_liminal=""
+  local remote_protected=""
+  local remote_current=""
+  local remote_name=""
+  local rebase_boundary=""
+  already_sorted=false
+  if put_wise_identify_rebase_boundary_and_remotes \
+    "${_action_desc:-bump}" "${_inhibit_exit_if_unidentified:-true}" \
+  ; then
+    REBASE_BOUNDARY="${rebase_boundary}"
+  else
+    # Cound not identify rebase boundary, and commits not sorted/signed.
+    REBASE_BOUNDARY="${PUT_WISE_REBASE_ALL_COMMITS:-ROOT}"
+    >&2 echo "ALERT: Could not identify the rebase boundary"
+    # Because put_wise_identify_rebase_boundary_and_remotes failed,
+    # `git put-wise push` will also fail and print help messages.
+    >&2 echo "- If you would like to use a custom boundary,"
+    >&2 echo "  consult the put-wise push output for options:"
+    >&2 echo "    git put-wise push"
+    >&2 echo "- Otherwise we suggest rebasing all commits"
+  fi
+
+  PW_PUSH_REMOTE_RELEASE="${remote_release}"
+}
+
+# ***
+
+is_put_wise_push_remote_same () {
+  local remote_name="$1"
+  local remote_branch="$2"
+
+  if ! is_git_put_wise_sort_and_sign_enabled; then
+    # Means PUT_WISE_SKIP_REBASE=true, or git-put-wise not found.
+
+    return 1
+  fi
+
+  if [ "${remote_name}/${remote_branch}" != "${PW_PUSH_REMOTE_RELEASE}" ]; then
+
+    return 1
+  fi
+
+  return 0
+}
+
+# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
 validate_and_normalize_version () {
   local tag_commit="$1"
