Refactor: Split function

diff --git a/bin/git-bump-version-tag b/bin/git-bump-version-tag
--- a/bin/git-bump-version-tag
+++ b/bin/git-bump-version-tag
@@ -1247,6 +1247,23 @@ check_prev_version_lt_later_version () {
     return 1
   fi
 
+  if is_version_lt_version "${prev_version}" "${later_version}"; then
+
+    return 0
+  fi
+
+  >&2 echo "ERROR: Cannot apply version to older commit larger than later version."
+  >&2 echo "- Apply version: “${prev_version}”"
+  >&2 echo "- Target commit: “${tag_commit}”"
+  >&2 echo "- Conlicts with: “${later_version}” (Smallest version after commit)"
+
+  return 1
+}
+
+is_version_lt_version () {
+  local prev_version="$1"
+  local later_version="$2"
+
   # 'pep440cmp' is optional, but we can do this without it.
 
   local prev_patch="$( \
@@ -1274,11 +1291,6 @@ check_prev_version_lt_later_version () {
       return 0
     fi
   fi
-
-  >&2 echo "ERROR: Cannot apply version to older commit larger than later version."
-  >&2 echo "- Apply version: “${prev_version}”"
-  >&2 echo "- Target commit: “${tag_commit}”"
-  >&2 echo "- Conlicts with: “${later_version}” (Smallest version after commit)"
 
   return 1
 }
