Refactor: Replace if-block with guard clause

diff --git a/bin/git-bump-version-tag b/bin/git-bump-version-tag
--- a/bin/git-bump-version-tag
+++ b/bin/git-bump-version-tag
@@ -1596,54 +1596,58 @@ insist_existing_version_and_new_version_are_opposing_types () {
   local version_tag="$2"
   local refname="$3"
 
+  if [ "${commit_version}" = "${version_tag}" ]; then
+
+    return 0
+  fi
+
   # Use case(s) for allowing two versions on the same commit:
   # - One pre-release, and one normal.
-  if [ "${commit_version}" != "${version_tag}" ]; then
-    local invalid_version=true
-    local error_hint=""
 
-    if is_version_gt_version "${version_tag}" "${commit_version}"; then
-      # Newer tag greater than existing tag.
-      if is_version_pre_release "${commit_version}"; then
-        # Existing version is pre-release.
-        if is_version_normal "${version_tag}"; then
-          # New version is normal.
-          invalid_version=false
+  local invalid_version=true
+  local error_hint=""
 
-          >&2 echo "BWARE: Double-tagging commit: Adding Normal version to Pre-release"
-        else
-          # Both versions are pre-release.
-          error_hint="- Hint: You can apply a normal version to this commit, but not pre-release"
-        fi
+  if is_version_gt_version "${version_tag}" "${commit_version}"; then
+    # Newer tag greater than existing tag.
+    if is_version_pre_release "${commit_version}"; then
+      # Existing version is pre-release.
+      if is_version_normal "${version_tag}"; then
+        # New version is normal.
+        invalid_version=false
+
+        >&2 echo "BWARE: Double-tagging commit: Adding Normal version to Pre-release"
       else
-        # Existing version is normal.
-        if is_version_pre_release "${version_tag}"; then
-          # New version is pre-release.
-          invalid_version=false
-
-          >&2 echo "BWARE: Double-tagging commit: Adding Pre-release version to Normal"
-        else
-          # Both versions are normal.
-          error_hint="- Hint: You can apply a pre-release version to this commit, but not normal"
-        fi
+        # Both versions are pre-release.
+        error_hint="- Hint: You can apply a normal version to this commit, but not pre-release"
       fi
     else
-      # Newer tag less than existing tag.
-      local version_type=""
-      if is_version_pre_release "${commit_version}"; then
-        version_type="normal"
+      # Existing version is normal.
+      if is_version_pre_release "${version_tag}"; then
+        # New version is pre-release.
+        invalid_version=false
+
+        >&2 echo "BWARE: Double-tagging commit: Adding Pre-release version to Normal"
       else
-        version_type="pre-release"
+        # Both versions are normal.
+        error_hint="- Hint: You can apply a pre-release version to this commit, but not normal"
       fi
-      error_hint="- Hint: You can try a ${version_type} version greater than ${commit_version}"
     fi
-
-    if ${invalid_version}; then
-      >&2 echo "ERROR: The target commit “${refname}” is already version-tagged: ${commit_version}"
-      >&2 echo "${error_hint}"
-
-      exit_1
+  else
+    # Newer tag less than existing tag.
+    local version_type=""
+    if is_version_pre_release "${commit_version}"; then
+      version_type="normal"
+    else
+      version_type="pre-release"
     fi
+    error_hint="- Hint: You can try a ${version_type} version greater than ${commit_version}"
+  fi
+
+  if ${invalid_version}; then
+    >&2 echo "ERROR: The target commit “${refname}” is already version-tagged: ${commit_version}"
+    >&2 echo "${error_hint}"
+
+    exit_1
   fi
 }
 
