Linting: Readability: UX: Swap same-valued variable usage

diff --git a/bin/git-bump-version-tag b/bin/git-bump-version-tag
--- a/bin/git-bump-version-tag
+++ b/bin/git-bump-version-tag
@@ -1242,7 +1242,7 @@ check_prev_version_lt_later_version () {
   fi
 
   if [ "${prev_version}" = "${later_version}" ]; then
-    >&2 echo "ERROR: Version “${prev_version}” already exists."
+    >&2 echo "ERROR: Version “${later_version}” already exists."
 
     return 1
   fi
