Improve: Ignore "v" version tag prefix when checking SemVer compliance
- The "v" prefix is not SemVer-compliant, but it's useful as a tag
  name prefix. I.e., the tag name is not SemVer compliant, but the
  part *after* the starting "v" must be SemVer compliant.

diff --git a/bin/git-bump-version-tag b/bin/git-bump-version-tag
--- a/bin/git-bump-version-tag
+++ b/bin/git-bump-version-tag
@@ -703,17 +703,21 @@ insist_next_version_gt_curr_version () {
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
+# CXREF: SemVer Perl regex, from the source, unaltered.
+#   https://semver.org/
+#   https://regex101.com/r/Ly7O1x/3/
 insist_new_version_semver_compliant () {
   local version_tag="$1"
 
-  local semver
+  local vless_version="$(echo "${version_tag}" | sed 's/^v//')"
 
+  local semver
   semver="$(
-    perl -ne "print if /${GITSMART_RE_SEMVERSPARTS}/" <<<"${version_tag}"
+    perl -ne "print if /${GITSMART_RE_SEMVERSPARTS}/" <<<"${vless_version}"
   )"
 
   if [ -z "${semver}" ]; then
-    >&2 echo "ERROR: The new version is not SemVer compliant: ${version_tag}"
+    >&2 echo "ERROR: The new version is not SemVer compliant: ${vless_version}"
 
     exit 1
   fi
