Improve: More exit trap within main, so not run if module sourced

diff --git a/bin/git-bump-version-tag b/bin/git-bump-version-tag
--- a/bin/git-bump-version-tag
+++ b/bin/git-bump-version-tag
@@ -2082,7 +2082,6 @@ exit_cleanup () {
     >&2 echo "- Hint: Enable \`set -x\` and run again..."
   fi
 }
-trap exit_cleanup EXIT
 
 # ***
 
@@ -2091,15 +2090,17 @@ main () {
   # for unattended CI runs.
   set -e
 
+  trap exit_cleanup EXIT
+
   source_deps "${BASH_SOURCE[0]}" || exit_1
 
   git_bump_tag_vers_push "$@"
+
+  # Unhook exit_cleanup.
+  trap - EXIT
 }
 
 if [ "$0" = "${BASH_SOURCE[0]}" ]; then
   main "${@}"
 fi
-
-# Unhook exit_cleanup.
-trap - EXIT
 
