Refactor: Move if-block to new function

diff --git a/bin/git-bump-version-tag b/bin/git-bump-version-tag
--- a/bin/git-bump-version-tag
+++ b/bin/git-bump-version-tag
@@ -1880,35 +1880,44 @@ resolve_remote_name () {
       || remote_name="$(git_upstream_parse_remote_name 2> /dev/null)"
     # If no such tracking branch, use sole remote if only one set.
     if [ -z "${remote_name}" ]; then
-      if [ -n "$(git remote -v)" ]; then
-        local push_remotes
-        push_remotes="$(git remote -v | grep -e ' (push)$')"
-
-        local num_remotes
-        num_remotes=$(echo "${push_remotes}" | wc -l)
-
-        if [ ${num_remotes} -eq 1 ]; then
-          # Just one remote; use it.
-          remote_name="$(echo "${push_remotes}" | sed 's/^\([^[:space:]]\+\).*/\1/')"
-        else
-          # This is the case: [ ${num_remotes} -gt 1 ]
-          >&2 echo "ERROR: Branch has no upstream, but more than one remote configured"
-          >&2 echo "- Please set a remote tracking branch and try again"
-          >&2 echo "  - E.g., if you've already pushed to the remote:"
-          >&2 echo "      git branch -u <remote/branch>"
-          >&2 echo "  - Or if this is your first push:"
-          >&2 echo "      git push -u <remote> <ref>:refs/heads/<branch>"
-          >&2 echo "- Failed to consider applying ${version_tag}"
-
-          return 1
-        fi
-      else
-        # Seems unnecessary:
-        #   >&2 echo "BWARE: There are no remotes. You can only version locally"
-        # Skip remote dealings.
-        remote_name="${BUMP_SKIP_REMOTE}"
-      fi
+      remote_name="$(resolve_remote_name_from_remotes "${version_tag}")" \
+        || return 1
     fi
+  fi
+
+  printf "%s" "${remote_name}"
+}
+
+resolve_remote_name_from_remotes () {
+  local version_tag="$1"
+
+  if [ -n "$(git remote -v)" ]; then
+    local push_remotes
+    push_remotes="$(git remote -v | grep -e ' (push)$')"
+
+    local num_remotes
+    num_remotes=$(echo "${push_remotes}" | wc -l)
+
+    if [ ${num_remotes} -eq 1 ]; then
+      # Just one remote; use it.
+      remote_name="$(echo "${push_remotes}" | sed 's/^\([^[:space:]]\+\).*/\1/')"
+    else
+      # This is the case: [ ${num_remotes} -gt 1 ]
+      >&2 echo "ERROR: Branch has no upstream, but more than one remote configured"
+      >&2 echo "- Please set a remote tracking branch and try again"
+      >&2 echo "  - E.g., if you've already pushed to the remote:"
+      >&2 echo "      git branch -u <remote/branch>"
+      >&2 echo "  - Or if this is your first push:"
+      >&2 echo "      git push -u <remote> <ref>:refs/heads/<branch>"
+      >&2 echo "- Failed to consider applying ${version_tag}"
+
+      return 1
+    fi
+  else
+    # Seems unnecessary:
+    #   >&2 echo "BWARE: There are no remotes. You can only version locally"
+    # Skip remote dealings.
+    remote_name="${BUMP_SKIP_REMOTE}"
   fi
 
   printf "%s" "${remote_name}"
