Feature: Normalize version (using dunamai, esp. for Poetry projects)
- Ensure that poetry-dynamic-versioning doesn't use a slightly different
  buid version than the tag, and use the same normalize library that it
  uses.

  - CXREF:

     https://github.com/mtkennerly/poetry-dynamic-versioning
     https://github.com/mtkennerly/dunamai

diff --git a/bin/git-bump-version-tag b/bin/git-bump-version-tag
--- a/bin/git-bump-version-tag
+++ b/bin/git-bump-version-tag
@@ -751,6 +751,20 @@ git_tvp_confirm_next () {
   [ "${the_choice}" != "y" ] && return 1 || return 0
 }
 
+git_tvp_confirm_normalize () {
+  local version_tag="$1"
+  local normal_vers="$2"
+
+  local msg="Okay to normalize “${version_tag}” → “${normal_vers}”"
+
+  local the_choice
+  the_choice=$(SKIP_PROMPT_NL=true ask_yesnoskip "${msg}" "Y")
+
+  [ $? -ne 0 ] && exit 1
+
+  [ "${the_choice}" != "y" ] && return 1 || return 0
+}
+
 git_tvp_confirm_delete () {
   local version_tag="$1"
   # local remote_name="$2"
@@ -1393,6 +1407,17 @@ prepare_push () {
     fi
   fi
 
+  # *** Normalize the version
+
+  local normal_vers
+  normal_vers="$(normalize_version "${VERSION_TAG}")"
+
+  if [ "${normal_vers}" != "${VERSION_TAG}" ]; then
+    if git_tvp_confirm_normalize "${VERSION_TAG}" "${normal_vers}"; then
+      VERSION_TAG="${normal_vers}"
+    fi
+  fi
+
   # *** Verify version order integrity between commits before and commits after
 
   # Verify tag_commit not versioned, or same as ${VERSION_TAG}.
@@ -1450,6 +1475,41 @@ prepare_push () {
     fi
     # else, means we're not moving remote branch HEAD.
   fi
+}
+
+# ***
+
+# Normalize the version otherwise a tool such as poetry-dynamic-versioning
+# might impress upon the build a version slightly different than what you
+# set. E.g., it'll change 1.1.1-a-1 to 1.1.1-a.1.
+#
+# https://github.com/mtkennerly/poetry-dynamic-versioning
+# https://github.com/mtkennerly/dunamai
+
+normalize_version () {
+  local orig_version="$1"
+
+  local prefixed_version="${orig_version}"
+  if [ "${orig_version}" = "${orig_version#v}" ]; then
+    prefixed_version="v${orig_version}"
+  fi
+
+  local temp_dir="$(mktemp -d /tmp/$(basename $0)-XXXXXXX)"
+  [ ! -d "${temp_dir}" ] && >&2 echo "ERROR: \`mktemp\` failed" && exit 1 || true
+
+  cd "${temp_dir}"
+
+  git init . -q
+  touch foo
+  git add foo
+  git commit -m foo -q
+  git tag "${prefixed_version}"
+
+  dunamai from git --style semver
+
+  cd - > /dev/null
+
+  /bin/rm -rf "${temp_dir}"
 }
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
