UX: Reformat (align) similar error messages

diff --git a/bin/git-bump-version-tag b/bin/git-bump-version-tag
--- a/bin/git-bump-version-tag
+++ b/bin/git-bump-version-tag
@@ -954,10 +954,10 @@ insist_prev_version_lt_later_version () {
     fi
   fi
 
-  >&2 echo "ERROR: Cannot apply version to older commit larger than later commit."
-  >&2 echo "- Desired version: ${prev_version}"
-  >&2 echo "- Target commit: ${tag_commit}"
-  >&2 echo "- Smallest version since commit: ${later_version}"
+  >&2 echo "ERROR: Cannot apply version to older commit larger than later version."
+  >&2 echo "- Apply version: “${prev_version}”"
+  >&2 echo "- Target commit: “${tag_commit}”"
+  >&2 echo "- Conlicts with: “${later_version}” (Smallest version after commit)"
 
   exit 1
 }
@@ -1001,10 +1001,10 @@ insist_prev_version_gt_earlier_version () {
     fi
   fi
 
-  >&2 echo "ERROR: Cannot apply version to older commit smaller than earlier commit."
-  >&2 echo "- Desired version: ${prev_version}"
-  >&2 echo "- Target commit: ${tag_commit}"
-  >&2 echo "- Largest version before commit: ${earlier_version}"
+  >&2 echo "ERROR: Cannot apply version to older commit smaller than earlier version."
+  >&2 echo "- Apply version: “${prev_version}”"
+  >&2 echo "- Target commit: “${tag_commit}”"
+  >&2 echo "- Conlicts with: “${earlier_version}” (Largest version before commit)"
 
   exit 1
 }
